// Generated by IB v0.4.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation EditController
@end

@implementation StkController
@end

@implementation Music
@end

@implementation Sting
@end

