// Generated by IB v0.3.5 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface EditController: UIViewController

@property IBOutlet UISlider * cuePoint;
@property IBOutlet UILabel * titleLabel;
@property IBOutlet UILabel * artistLabel;

-(IBAction) viewDidLoad;
-(IBAction) dismiss;
-(IBAction) loadTrack;
-(IBAction) mediaPickerDidCancel:(id) mediaPicker;
-(IBAction) setCue;

@end

@interface StkController: UIViewController

@property IBOutlet UILabel * titleLabel;
@property IBOutlet UITableView * playlistTable;

-(IBAction) viewDidLoad;
-(IBAction) play;
-(IBAction) stop;
-(IBAction) loadSting:(id) mediaItem;
-(IBAction) setCue:(id) cuePoint;
-(IBAction) getCue;
-(IBAction) iPodPlay;
-(IBAction) iPodPause;
-(IBAction) iPodPrevious;
-(IBAction) iPodNext;
-(IBAction) getPlaylist;

@end

@interface StingPlayer
-(IBAction) initialize;
-(IBAction) play;
-(IBAction) stop;
-(IBAction) loadSting:(id) mediaItem;
-(IBAction) setCue:(id) cuePoint;
-(IBAction) getCue;

@end

