// Generated by IB v0.4.3 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <AVFoundation/AVFoundation.h>
#import <MediaPlayer/MediaPlayer.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface EditController: UIViewController

@property IBOutlet UIScrollView * editScrollView;
@property IBOutlet UIView * editView;
@property IBOutlet UILabel * titleLabel0;
@property IBOutlet UILabel * artistLabel0;
@property IBOutlet UIView * waveView0;
@property IBOutlet UILabel * titleLabel1;
@property IBOutlet UILabel * artistLabel1;
@property IBOutlet UIView * waveView1;
@property IBOutlet UILabel * titleLabel2;
@property IBOutlet UILabel * artistLabel2;
@property IBOutlet UIView * waveView2;
@property IBOutlet UIPickerView * playlistPicker;

-(IBAction) viewDidLoad;
-(IBAction) dismiss;
-(IBAction) loadTrack;
-(IBAction) loadTrack0;
-(IBAction) loadTrack1;
-(IBAction) loadTrack2;
-(IBAction) updateLabels;
-(IBAction) updateWaveURL:(id) i;
-(IBAction) mediaPickerDidCancel:(id) mediaPicker;
-(IBAction) numberOfComponentsInPickerView:(id) pickerView;

@end

@interface StkController: UIViewController

@property IBOutlet UILabel * titleLabel0;
@property IBOutlet UILabel * titleLabel1;
@property IBOutlet UILabel * titleLabel2;
@property IBOutlet UITableView * playlistTable;
@property IBOutlet UIScrollView * stingScrollView;
@property IBOutlet UIPageControl * stingPage;

-(IBAction) viewDidLoad;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) viewWillDisappear:(id) animated;
-(IBAction) play;
-(IBAction) stop;
-(IBAction) iPodPlay;
-(IBAction) iPodPause;
-(IBAction) iPodPrevious;
-(IBAction) iPodNext;
-(IBAction) updateTitle;
-(IBAction) updateTable;
-(IBAction) scrollViewDidEndDecelerating:(id) scrollView;

@end

@interface Engine: NSObject
-(IBAction) initialize;
-(IBAction) playSting:(id) selectedSting;
-(IBAction) stopSting;
-(IBAction) playiPod;
-(IBAction) playiPodItem:(id) index;
-(IBAction) pauseiPod;

@end

@interface Music: NSObject
-(IBAction) initialize:(id) selectedPlaylist;
-(IBAction) play;
-(IBAction) pause;
-(IBAction) previous;
-(IBAction) next;
-(IBAction) playItem:(id) index;
-(IBAction) nowPlayingItem;
-(IBAction) getNamedPlaylist:(id) name;
-(IBAction) getAllPlaylists;
-(IBAction) usePlaylist:(id) index;

@end

@interface Sting: NSObject
-(IBAction) play;
-(IBAction) stop;
-(IBAction) loadSting:(id) mediaItem;
-(IBAction) setCue:(id) cuePoint;
-(IBAction) getCue;

@end

