// Generated by IB v0.3.5 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface EditController: UIViewController

@property IBOutlet UISlider * cuePoint;
@property IBOutlet UILabel * titleLabel;
@property IBOutlet UILabel * artistLabel;
@property IBOutlet UIPickerView * playlistPicker;

-(IBAction) viewDidLoad;
-(IBAction) dismiss;
-(IBAction) loadTrack;
-(IBAction) setCue;
-(IBAction) mediaPickerDidCancel:(id) mediaPicker;
-(IBAction) numberOfComponentsInPickerView:(id) pickerView;

@end

@interface StkController: UIViewController

@property IBOutlet UILabel * titleLabel;
@property IBOutlet UITableView * playlistTable;

-(IBAction) viewDidLoad;
-(IBAction) play;
-(IBAction) stop;
-(IBAction) iPodPlay;
-(IBAction) iPodPause;
-(IBAction) iPodPrevious;
-(IBAction) iPodNext;
-(IBAction) updateTitle;
-(IBAction) updateTable;

@end

@interface Music
-(IBAction) initialize;
-(IBAction) play;
-(IBAction) pause;
-(IBAction) Previous;
-(IBAction) Next;
-(IBAction) playItem:(id) index;
-(IBAction) getPlaylist;
-(IBAction) getAllPlaylists;
-(IBAction) usePlaylist:(id) index;

@end

@interface Sting
-(IBAction) initialize;
-(IBAction) play;
-(IBAction) stop;
-(IBAction) loadSting:(id) mediaItem;
-(IBAction) setCue:(id) cuePoint;
-(IBAction) getCue;

@end

